apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress
  namespace: dev
spec:
  rules:
      - http:
          paths:
            - path: /kafka
              backend:
                serviceName: kafka-service
                servicePort: 80
