---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: ingress-nginx
spec:
  ports:
    - name: tcp
      port: 8080
      targetPort: 3000
  selector:
    app: kafka